[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.backends._legacy:_Backend"

[project]
name = "ppg2ecg"
version = "0.1.0"
description = "Photoplethysmogram to 12-Lead ECG Reconstruction"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
